# Generated by Django 3.0.1 on 2019-12-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_Title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('description_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
